### ISSUE TITLE
Actions on several files at once

### ISSUE THREAD

**Issue by sguyader** [m0g/ansel#1]
It would be nice to be able to work on several files at once, like for example giving a specific tag to several files by selecting them and adding the tag. It looks like we can't select several files simultaneously.
Also, some simple tasks such as tagging can often be done without the need to open the specific file, tagging should be possible to a file which is selected, not necessarily open
Ansel v0.37.3.

**Comment by m0g** [comment]
Hey,

I'm planning on implementing that functionality in the near future. I'll update the issue when the it will be fully implemented.

Thanks for your interest

**Comment by m0g** [comment]
Hey @sguyader I've started implementing multiple action on a file at once: https://github.com/m0g/ansel/commit/c8ddc04db35318578918f8ab7b1c8a5c3a64850e

If you run from master, you should see it

**Comment by sguyader** [comment]
Hey @m0g I didn't see your message... I'm going to try that.

**Comment by m0g** [comment]
:+1:
