### ISSUE TITLE
DateTimeOriginal ignored

### ISSUE THREAD

**Issue by asp** [m0g/ansel#2]
Ansel appears to only read the image DateTime field and ignore DateTimeOriginal.

According to the MWG Guidelines, Exif.Image.DateTime is the "Modification date of the digital image file" while Exif.Photo.DateTimeOriginal is the "Creation date of the intellectual content (e.g. the photograph)". 

Clarification on Date/Time handling can be found in section 5.3 of the guidelines:

    http://www.metadataworkinggroup.org/pdf/mwg_guidance.pdf#page=37

As a side note, the "Exif.Image" and "Exif.Photo" prefixes are the vocabulary used in exiv2. Those prefixes do not appear in the exif specs nor in the MWG document.

**Comment by m0g** [comment]
Hi and thanks for your input,

I've replaced `Exif.Image.DateTime` with `Exif.Photo.DateTimeOriginal`
